import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migration1721199147217 implements MigrationInterface {
  name = 'Migration1721199147217';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "user" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "firstName" character varying NOT NULL, "surname" character varying NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "description" character varying NOT NULL, "nickname" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")); COMMENT ON COLUMN "user"."id" IS 'Идентификатор пользователя'; COMMENT ON COLUMN "user"."firstName" IS 'Имя'; COMMENT ON COLUMN "user"."surname" IS 'Фамилия'; COMMENT ON COLUMN "user"."email" IS 'Электронная почта'; COMMENT ON COLUMN "user"."passwordHash" IS 'Электронная почта'; COMMENT ON COLUMN "user"."description" IS 'Описание профиля'; COMMENT ON COLUMN "user"."nickname" IS 'Никнейм'`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "user"`);
  }
}
