import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migration1721655827444 implements MigrationInterface {
  name = 'Migration1721655827444';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "file" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "mimeType" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id")); COMMENT ON COLUMN "file"."id" IS 'Идентификатор файла'; COMMENT ON COLUMN "file"."name" IS 'Название'; COMMENT ON COLUMN "file"."mimeType" IS 'MIME тип'`,
    );
    await queryRunner.query(
      `CREATE TABLE "user" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "firstName" character varying NOT NULL, "surname" character varying NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "description" character varying NOT NULL, "nickname" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "photoId" integer, CONSTRAINT "REL_75e2be4ce11d447ef43be0e374" UNIQUE ("photoId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")); COMMENT ON COLUMN "user"."id" IS 'Идентификатор пользователя'; COMMENT ON COLUMN "user"."firstName" IS 'Имя'; COMMENT ON COLUMN "user"."surname" IS 'Фамилия'; COMMENT ON COLUMN "user"."email" IS 'Электронная почта'; COMMENT ON COLUMN "user"."passwordHash" IS 'Электронная почта'; COMMENT ON COLUMN "user"."description" IS 'Описание профиля'; COMMENT ON COLUMN "user"."nickname" IS 'Никнейм'`,
    );
    await queryRunner.query(
      `ALTER TABLE "user" ADD CONSTRAINT "FK_75e2be4ce11d447ef43be0e374f" FOREIGN KEY ("photoId") REFERENCES "file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "user" DROP CONSTRAINT "FK_75e2be4ce11d447ef43be0e374f"`,
    );
    await queryRunner.query(`DROP TABLE "user"`);
    await queryRunner.query(`DROP TABLE "file"`);
  }
}
