import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migration1722415149087 implements MigrationInterface {
  name = 'Migration1722415149087';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "post_tag" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_a1a7ab675d35354edf3611f7d96" UNIQUE ("name"), CONSTRAINT "PK_3364a9669ea4b632cff0eb01944" PRIMARY KEY ("id")); COMMENT ON COLUMN "post_tag"."id" IS 'Идентификатор тега'; COMMENT ON COLUMN "post_tag"."name" IS 'Название тега'`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "post_tag"`);
  }
}
