import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migration1722946914576 implements MigrationInterface {
  name = 'Migration1722946914576';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "post_comment" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "text" character varying NOT NULL, "userId" integer NOT NULL, "postId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_5a0d63e41c3c55e11319613550c" PRIMARY KEY ("id")); COMMENT ON COLUMN "post_comment"."id" IS 'Идентификатор комментария'; COMMENT ON COLUMN "post_comment"."text" IS 'Текст комментария'`,
    );
    await queryRunner.query(
      `ALTER TABLE "post_comment" ADD CONSTRAINT "FK_5675870bd3124aeeaa476256062" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "post_comment" ADD CONSTRAINT "FK_c7fb3b0d1192f17f7649062f672" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "post_comment" DROP CONSTRAINT "FK_c7fb3b0d1192f17f7649062f672"`,
    );
    await queryRunner.query(
      `ALTER TABLE "post_comment" DROP CONSTRAINT "FK_5675870bd3124aeeaa476256062"`,
    );
    await queryRunner.query(`DROP TABLE "post_comment"`);
  }
}
