import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migration1722238856658 implements MigrationInterface {
  name = 'Migration1722238856658';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "post" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" character varying NOT NULL, "text" character varying NOT NULL, "userId" integer, "imageId" integer, CONSTRAINT "REL_34a189b53541d1ece1750cc471" UNIQUE ("imageId"), CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id")); COMMENT ON COLUMN "post"."id" IS 'Идентификатор поста'; COMMENT ON COLUMN "post"."title" IS 'Заголовок'; COMMENT ON COLUMN "post"."text" IS 'Основной текст поста'`,
    );
    await queryRunner.query(
      `ALTER TABLE "post" ADD CONSTRAINT "FK_5c1cf55c308037b5aca1038a131" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "post" ADD CONSTRAINT "FK_34a189b53541d1ece1750cc4717" FOREIGN KEY ("imageId") REFERENCES "file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "post" DROP CONSTRAINT "FK_34a189b53541d1ece1750cc4717"`,
    );
    await queryRunner.query(
      `ALTER TABLE "post" DROP CONSTRAINT "FK_5c1cf55c308037b5aca1038a131"`,
    );
    await queryRunner.query(`DROP TABLE "post"`);
  }
}
